# Site settings
title: VCOM
email:
description: VCOM is a model created as part of UCSF's Malaria Elimination Initiative. Its goal is to help policy makers evaluate mosquito-control interventions to make informed decisions on which combinations are more promising in certain settings.
url: "" # the base hostname & protocol for your site

# User setting
owner: Malaria Elimination Initiative
email:  samson.kiware@ucsf.edu
facebook_username:
twitter_username:
github_username: chipdelmal
address:
  - line:
  - line:
  # Feel free to add more lines here 
telephone:
copyright:

# API settings
google_api_key:

# Build settings
markdown: kramdown